### ISSUE TITLE
Cannot find SourceMap 'data:application/json;base64

### ISSUE THREAD

**Issue by samdenty99** [mac-s-g/react-json-view#174]
```log
client?e8a6:147 [WDS] Warnings while compiling.
warnings @ client?e8a6:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
SockJS._transportMessage @ main.js:272
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
22:48:03.247 client?e8a6:153 ./node_modules/react-json-view/dist/main.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(a))))+"': Error: Can't resolve './data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(a))))+"' in 'XXX'
 @ ./components/Projects/Data/index.jsx 16:0-40
 @ ./components/Projects/index.jsx
 @ ./components/index.jsx
 @ ./main.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch ./main.jsx
```

**Version:** 1.16.1
**React:** 16.2.0

**Comment by mac-s-g** [comment]
@samdenty99 
I'm not really sure where to start.
Is this something that just started happening with 1.16.1?

**Comment by mac-s-g** [comment]
@samdenty99 is this an issue?

**Comment by mac-s-g** [comment]
closing this issue

**Comment by Tenga** [comment]
@mac-s-g Our team has also encountered this issue with v1.17.0, however we also tried v1.16.0 to attempt answer your question to the original author of this bug, and the same problem is there. :)

```
WARNING in ./node_modules/react-json-view/dist/main.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(a))))+"': Error: Can't resolve './data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(a))))+"' in '/Users/xxx/xxx/xxx/node_modules/react-json-view/dist'
```

I've taken a look at the `/dist/main.js` where this occurs and it seems there is a block of code that seems to be responsible for generating the inline source map (?), however, due to it's formatting and as it the string within contains `/*#sourceMappingURL=`, it seems to be interpreted by webpack as the actual source map comment.

To me, it seems like this is getting packed into the dist by accident as I'm not sure why this would be here in the first place.

If it's of any help, the `/dist/main.js` that we end up with is [here](https://pastebin.com/BQQdhtJ4) and you can find what I'm talking about and the source of the error by searching for `sourceMappingURL`.
