### ISSUE TITLE
Uncaught EvalError after updating to 1.20.0

### ISSUE THREAD

**Issue by ulieckstein** [mac-s-g/react-json-view#316]
We are running a website with a CSP that does not allow eval functionality for javascript. After updating react-json-view from 1.19.1 to 1.20.0 we get EvalErrors when loading the page.

**Comment by asherf** [comment]
Seeing this on our env too, also happens on v1.20.2

**Comment by mac-s-g** [comment]
hmm that's unfortunate.  i don't believe rjv is dong any eval directly.  but 1.20 came with major updates to just about every dependency.

at 1.19.x, npm audit was reporting a ton of security vulnerabilities (a few critical).

at 1.20.2, all of those have been resolved. 

so overall, ^1.20.2 should be safer to use - but nobody feels good about eval being used.

any idea where or what dependency the eval is coming from?

the more information you can give me about where the issue is coming from, the faster i can get it addressed.

just fyi - i won't be able to investigate until this weekend at the earliest.  so the quick fix is to downgrade to 1.19.1 until i can publish a fix.

**Comment by asherf** [comment]
@mac-s-g I am not sure where this is coming from but I was able to "fix" by reverting to an older version `1.19.1` 
Even though I have source maps I am not able to trace the error back to the source (sorry, I am more of a backend guy and my JS knowledge is limited).
this is what I see in dev tools
<img width="832" alt="Screen Shot 2021-01-20 at 5 32 56 PM" src="https://user-images.githubusercontent.com/1268088/105264751-8a886e00-5b45-11eb-945d-38bace173346.png">
<img width="753" alt="Screen Shot 2021-01-20 at 5 30 53 PM" src="https://user-images.githubusercontent.com/1268088/105264815-8e1bf500-5b45-11eb-8f9b-74341cf37c67.png">

I really hope this helps.
this is w/ the latest version (1.20.2)

**Comment by mac-s-g** [comment]
extra detail is always appreciated! thanks @asherf !  i'll let you know when i have a fix on the way

**Comment by mac-s-g** [comment]
@asherf i think this is resolved with #318 
it's difficult for me to test though so i'm not 100% positive.

can you try upgrading to 1.20.3 and let me know if you still see the issue?

**Comment by mac-s-g** [comment]
or @ulieckstein could verify as well.  i'm like 90% sure this is resolved.

**Comment by asherf** [comment]
@mac-s-g I have tested the new version and it fixes this issue!
Thank you for fixing this so quickly!

**Comment by mac-s-g** [comment]
resolved by #318

**Comment by ulieckstein** [comment]
the error is gone, thanks @mac-s-g
