### ISSUE TITLE
boolean type will be converted to string after onEdit?

### ISSUE THREAD

**Issue by wood3n** [mac-s-g/react-json-view#356]
After edit a value of boolean type, it will convert to string. How to fix this?

![image](https://user-images.githubusercontent.com/31716713/116344326-9f496180-a818-11eb-8ca2-366f64d5520e.png)

![image](https://user-images.githubusercontent.com/31716713/116344355-abcdba00-a818-11eb-9d5a-101c9f5449e5.png)

**Comment by Aldinco** [comment]
Hi! Fortunately that functionality does exist, but it's a bit hidden. When you're dealing with boolean values (meaning if you write `true` or `false` in the textbox) another checkmark will popup just below the normal one. Click on that instead and it will maintain the boolean value instead of turning it into a string. Here's a gif:

![bolean](https://user-images.githubusercontent.com/33787852/116825044-a3b1a980-ab8d-11eb-920d-0fb539fbafde.gif)

Also, [here's a link to Code Sandbox](https://codesandbox.io/s/practical-flower-sp7f0?file=/src/App.js) where you can play around with it:
