### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by shanielh** [mac-s-g/react-json-view#63]
Hi.

Is there any support for custom themes? Couldn't find in the readme / source code.

**Comment by mac-s-g** [comment]
not currently, i'll use this issue to track support for custom base-16 themes

**Comment by shanielh** [comment]
If you want I can hack something in the weekend and pull request :-)?

**Comment by mac-s-g** [comment]
okay, I'm cool with that.  You're just interested in providing a custom color theme, right?

I might link a PR and let you review.

**Comment by shanielh** [comment]
Yes.

**Comment by mac-s-g** [comment]
Turns out I was supporting this, it was just not documented.  (love when that happens)

I did put up a PR to add some input validation and a custom theme example.

I commented on the example in the pr #64 

I'll also update the README with a little more info.

If you want to expand on the customization support, I'd love that!

**Comment by mac-s-g** [comment]
published v 1.9.5 which includes input validation for custom themes.

**Comment by mac-s-g** [comment]
i also added this: https://github.com/mac-s-g/react-json-view#use-your-own-theme

**Comment by shanielh** [comment]
Thank you very much :+1:
