### ISSUE TITLE
The updated_src after an onEdit restores the initial props.src instead of the current props.src

### ISSUE THREAD

**Issue by shybyte** [mac-s-g/react-json-view#95]
If you change the src prop and rerender the component it will correctly view the new src. But after a manual edit it will (aside from the manual changed value) restore the initial src prop.

https://codepen.io/shybyte/pen/PKWWqo

I'm already working on a pull request.

**Comment by mac-s-g** [comment]
i think i was a little hasty in pushing this code.

i see what the issue is after looking closer.

you want to take `src` update management out of the component and control changes externally (using callbacks and re-renders).

the reason why `src`  is managed by `state` rather than just `props` is because the component handles `src` internally once it's been rendered.  that idea was to make `onEdit`, `onAdd` and `onDelete` work out of the box.

I'm going to undo the change via pr #98 and open this issue back up.

HOWEVER - your changes are consistent with standard react design patterns.

I'm going to work on controlling `src` with `props` only and indicate the change with a major version update (2.0.0).

that will allow me to remove all the state management complexity and hopefully get rid of `ObjectAttributes` global storage.  the only downside is that users will have to intentionally capture edits via callback methods, update `src` prop and rerender the component to get edits working.  

The downside is an upside.  This is the type of behavior i'd expect from a react component.

more on this to come.  I published  1.11.5 to npm with your changes.  you can use that for now.

**Comment by mac-s-g** [comment]
before I make test-breaking changes, can you test out #100 and let me know if it solves the original issue you pointed out?

**Comment by shybyte** [comment]
#100 works great for me!  Thanks!
